theme = "sonokai"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
true-color = true
rulers = [80]
bufferline = "always"
completion-replace = true
color-modes = true
shell = ["zsh", "-c"]

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme sonokai"]


[keys.normal.space]
w = ":write"
q = ":quit"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "separator", "selections", "position", "file-encoding", "separator", "file-line-ending", "separator", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true

[editor.lsp]
snippets = true

